### ISSUE TITLE
TypeError: describe_rate() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by scottleibrand** [bewest/decoding-carelink#51] opened 2014-11-29 05:34 UTC
https://gist.github.com/scottleibrand/4bbc0d8b230b80104f21

**Comment by bewest** [comment] 2015-03-31 20:11
Duplicate of https://github.com/bewest/decoding-carelink/issues/56, should be fixed-ish, complain loudly if not.

**Closed by bewest** 2015-03-31 20:11 UTC
